# docker-compose.yml
version: "3"
services:
    db:
      container_name: "${APP_NAME}-mariadb"
      image: mariadb/server:10.5
      restart: always
      # be sure to run `docker volume rm dev_dev_conf` when changing envs
      environment:
        MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
        MARIADB_DATABASE: "${MARIADB_DATABASE}"
        MARIADB_USER: "${MARIADB_USER}"
        MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
      ports:
          - "3306:3306"
      volumes:
          - db_data:/var/lib/mysql
          - db_conf:/etc/mysql

    wpp-connect:
      container_name: "${APP_NAME}-wpp-connect"
      build: 
        context: ./wpp-connect-server
      ports:
          - "21465:21465"

        
volumes:
    db_data:
    db_conf: